# Generated by Django 2.1.5 on 2019-03-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouping',
            name='group',
        ),
        migrations.AddField(
            model_name='grouping',
            name='group',
            field=models.ManyToManyField(to='app.groups_name'),
        ),
    ]
