# Generated by Django 2.1.5 on 2019-03-11 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190311_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 17, 24, 34, 772440), verbose_name='任务添加时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='待审核', max_length=10, verbose_name='任务状态'),
        ),
    ]
