# Generated by Django 2.1.5 on 2019-03-12 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190311_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='typ',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='任务类别'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 14, 38, 1, 508052), verbose_name='任务添加时间'),
        ),
    ]
