# Generated by Django 2.1.5 on 2019-03-15 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190312_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_str', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='唯一标识')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件路径')),
                ('status', models.CharField(default='未发送', max_length=10, verbose_name='任务状态')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='uuid_str',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 10, 38, 5, 179564), verbose_name='任务添加时间'),
        ),
    ]
