# Generated by Django 2.1.5 on 2019-03-15 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190315_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 10, 39, 7, 457401), verbose_name='任务添加时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='group_name',
            field=models.TextField(blank=True, null=True, verbose_name='群组名字'),
        ),
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='消息'),
        ),
    ]
