# Generated by Django 2.1.5 on 2019-03-15 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190315_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(blank=True, default='未发送', max_length=10, null=True, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 10, 51, 22, 70178), verbose_name='任务添加时间'),
        ),
    ]
