# Generated by Django 2.1.5 on 2019-03-15 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190315_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='message_type',
            field=models.CharField(blank=True, default='文字', max_length=10, null=True, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 11, 8, 57, 943727), verbose_name='任务添加时间'),
        ),
    ]
